services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: inforepository_app
        restart: unless-stopped
        networks:
            - app_network
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:latest
        container_name: inforepository_nginx
        restart: unless-stopped
        networks:
            - app_network
        ports:
            - "8080:80" # Map port 80 inside the container to port 8080 on the host
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    db:
        image: mariadb:latest
        container_name: inforepository_db
        restart: unless-stopped
        networks:
            - app_network
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: inforepository_redis
        restart: unless-stopped
        networks:
            - app_network
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

networks:
    app_network:
        driver: bridge

volumes:
    db_data:
    redis_data:
